#!/bin/sh

export PATH="$PATH:./node_modules/.bin"
export PATH="/home/jared/.cargo/bin:$PATH"
export PATH=$PATH:/usr/local/go/bin

# Init NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# check for miniconda vs. anaconda3
if [ -d "$HOME/miniconda3" ]; then
	__conda_setup="$('/home/jared/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "/home/jared/miniconda3/etc/profile.d/conda.sh" ]; then
			. "/home/jared/miniconda3/etc/profile.d/conda.sh"
		else
			export path="/home/jared/miniconda3/bin:$path"
		fi
	fi
	unset __conda_setup

# Check for .miniconda
elif [ -d "$HOME/.miniconda3" ]; then
	__conda_setup="$('/home/jared/.miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "/home/jared/.miniconda3/etc/profile.d/conda.sh" ]; then
			. "/home/jared/.miniconda3/etc/profile.d/conda.sh"
		else
			export path="/home/jared/.miniconda3/bin:$path"
		fi
	fi
	unset __conda_setup

# Check for anaconda3
elif [ -d "$HOME/anaconda3" ]; then
	__conda_setup="$('/home/jared/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "/home/jared/anaconda3/etc/profile.d/conda.sh" ]; then
			. "/home/jared/anaconda3/etc/profile.d/conda.sh"
		else
			export PATH="/home/jared/anaconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup

fi
