#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH=$PATH:/usr/local/go/bin
export PATH="$HOME/.local/bin":$PATH
# export PATH="$PATH:$HOME/.local/share/nvim/lsp_servers"
export PATH="$PATH:$HOME/.local/share/nvim/mason"
export PATH="$PATH:$HOME/.nvm/versions/node/v20.13.1/bin"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
#export PATH="$PATH:./node_modules/.bin"
export PATH="$HOME/.cargo/bin:$PATH"

# Set JAVA_HOME if a JDK is installed
if [ -x "$(brew --prefix openjdk)/libexec/openjdk.jdk/Contents/Home" ]; then
  export JAVA_HOME="$(brew --prefix openjdk)/libexec/openjdk.jdk/Contents/Home"
fi
