#!/bin/sh

export PATH="$PATH:./node_modules/.bin"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH=$PATH:/usr/local/go/bin

# opam configuration
[[ ! -r $HOME/.opam/opam-init/init.zsh ]] || source $HOME/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# Init NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Ocaml
[[ ! -r $HOME/.opam/opam-init/init.zsh ]] || source $HOME/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# check for miniconda vs. anaconda3
if [ -d "$HOME/miniconda3" ]; then
	__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
			. "$HOME/miniconda3/etc/profile.d/conda.sh"
		else
			export path="$HOME/miniconda3/bin:$path"
		fi
	fi
	unset __conda_setup

# Check for .miniconda
elif [ -d "$HOME/miniconda" ]; then
	__conda_setup="$("$HOME/miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "$HOME/miniconda/etc/profile.d/conda.sh" ]; then
			. "$HOME/miniconda/etc/profile.d/conda.sh"
		else
			export path="$HOME/miniconda/bin:$path"
		fi
	fi
	unset __conda_setup

# Check for .miniconda
elif [ -d "$HOME/.miniconda3" ]; then
	__conda_setup="$("$HOME/.miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "$HOME/.miniconda3/etc/profile.d/conda.sh" ]; then
			. "$HOME/.miniconda3/etc/profile.d/conda.sh"
		else
			export path="$HOME/.miniconda3/bin:$path"
		fi
	fi
	unset __conda_setup

# Check for anaconda3
elif [ -d "$HOME/anaconda3" ]; then
	__conda_setup="$("$HOME/anaconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
			. "$HOME/anaconda3/etc/profile.d/conda.sh"
		else
			export PATH="$HOME/anaconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup

fi
