#!/bin/sh
alias vi='nvim'
alias lg='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias python="python3"
alias tv="swaymsg output HDMI-A-1 enable mode 3840x2160@120.000Hz"
alias tv_on="swaymsg output HDMI-A-1 enable mode 3840x2160@120.000Hz"
alias tv_off="swaymsg output HDMI-A-1 disable"
alias mc="mc -u"

# For rebooting and shutting down
alias srn="sudo reboot now"
alias ssn="sudo shutdown now"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -10'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -10'

# Better ls with colors
if [ -x "$(command -v exa)" ]; then
    alias ls="exa"
    alias la="exa --long --all --group --header --accessed --icons --classify"
    alias ll="exa --long --group --header --accessed --icons --classify"
fi

# Better ls with colors
if [ -x "$(command -v eza)" ]; then
    alias ls="eza"
    alias la="eza --long --all --group --header --accessed --icons --classify"
    alias ll="eza --long --group --header --accessed --icons --classify"
fi

# Better dnf
if [ -x "$(command -v dnf5)" ]; then
    alias dnf="dnf5"
fi

# Better cat with colors
if [ -x "$(command -v batcat)" ]; then
    alias cat="batcat"
fi

# Delete things to the trash
if [ -x "$(command -v trash)" ]; then
    alias dd="trash"
    alias delete="trash"
    alias rm="trash -i"
fi


# Load heavy exports
alias heavy='zsh_add_file "zsh-heavy-exports"'
alias conda-load='zsh_add_file "zsh-heavy-exports"'
alias nvm-load='zsh_add_file "zsh-heavy-exports"'

# Git
if [ -x "$(command -v lazygit)" ]; then
	alias lg="lazygit"
fi

# FD aliases
if [ -x "$(command -v fdfind)" ]; then
	alias fd="fdfind"
fi

# FZF aliases
alias fzff='print -z $(fd --type f --strip-cwd-prefix --hidden --exclude .git | fzf)'
alias fzv='nvim -z $(fd --type f --strip-cwd-prefix --hidden --exclude .git | fzf)'
alias fzfd='cd "$(fd --type d --strip-cwd-prefix --hidden --exclude .git | fzf)"'


# Do a search through history
alias hg='print -z $(sort ~/.config/zsh/.zsh_history | uniq -c | fzf +s --tac | sed -E "s/ *[0-9]*\*? *//")'

# source gpt venv
alias py-cloud="source ~/.venv/gpt-venv/bin/activate"

# Clear the terminal
alias cl="clear"
alias cln="clear && echo '' && fastfetch -s \
	Title:Separator:Break:OS:Host:Kernel:Uptime:Packages:Shell:Display:WM:Terminal:CPU:GPU:Memory:Disk:LocalIp:Break:Colors:Break \
	--disk-show-external false"

# Quick projects
alias nvimrc='cd ~/.config/nvim/ && nvim'
alias notes='cd ~/Nextcloud/Notes/ && nvim'
alias zshrc="cd ~/.config/zsh/ && nvim"

# Blogging
alias blog='cd ~/Website_Projects/jaredsblog/jaredsblog/'
alias django='source ~/.pyenv/django/bin/activate'
alias jb-run='blog && django && python manage.py runserver'
alias jb-tail='blog && django && python manage.py tailwind start'
alias jb-vim='blog && django && nvim'
alias jb-mark='blog && django && python scripts/copy_obsidian.py /home/jared/Nextcloud/Notes/Blog && python convert_markdown.py'

# Quick export of testamentto
alias wp="code /var/www/contracts/"
alias contracts="cd /var/www/contracts/ && nvim"
alias wp-contracts-prod="~/.jaredbs/wp-contracts-prod.sh"
alias wp-contracts-razer="~/.jaredbs/wp-contracts-razer.sh"
alias wp-alshaya-prod="~/.jaredbs/wp-alshaya-prod.sh"

# For work
alias extreme="rg "pass" Nextcloud/Notes/HungerStation/Accesses.md"
